// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Healthz implements healthz operation.
//
// Servers health check endpoint.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context) (r *Healthy, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorRespStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorRespStatusCode) {
	r = new(ErrorRespStatusCode)
	return r
}
